name: priv_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.0
  location: ^6.0.1
  google_maps_flutter: ^2.5.0
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0
  flutter_notification_listener: ^1.3.2
  firebase_database: ^10.4.9
  fast_contacts: ^3.1.3
  battery_plus: ^5.0.3
  device_apps: ^2.2.0
  device_info_plus: ^9.1.2
  connectivity_plus: ^6.0.3
  zego_uikit_prebuilt_call: ^4.9.0  
  flutter_vibrate: ^1.3.0





  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
flutter:

  uses-material-design: true

